name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore "CrossSigEngine.sln"

      - name: Build
        run: dotnet build "CrossSigEngine.sln" -c Release --no-restore

      - name: Test
        run: dotnet test "CrossSigEngine.Tests/CrossSigEngine.Tests.csproj" -c Release --no-build --logger trx

      - name: Publish Web
        run: dotnet publish "CrossSigEngine.Web/CrossSigEngine.Web.csproj" -c Release -o out/web --no-build

      - name: Publish CLI
        run: dotnet publish "CrossSigEngine.Cli/CrossSigEngine.Cli.csproj" -c Release -o out/cli --no-build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: crosssigengine-artifacts
          path: |
            out/web
            out/cli

  smoke:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Run smoke tests
        shell: pwsh
        run: |
          ./scripts/smoke.ps1 -SkipBuild
